name: Shakedown Smoke Tester
author: Rob Whitby
description: Simple smoke test framework for http applications

inputs:
  tests:
    description: path to test file e.g. sample-test.sh
    required: true
  url:
    description: base url to test e.g. https://duckduckgo.com
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        SHAKEDOWN_URL: ${{ inputs.url }}
        TESTS: ${{ inputs.tests }}
      run: |
        [ -f "${TESTS}" ] || { echo "error: test file '${TESTS}' does not exist" >&2; exit 1; }
        [ -n "${SHAKEDOWN_URL}" ] || { echo "error: 'url' required" >&2; exit 1; }
        export PATH="${{ github.action_path }}:${PATH}"
        bash "${TESTS}"

branding:
  icon: check
  color: green
